logging:
  level:
    root: INFO
server:
  port: 8080
  servlet:
    context-path: /api/currency-service
spring:
  application:
  name: Currency-Service
  datasource:
    url: jdbc:h2:mem:currency-db
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  liquibase:
    url: jdbc:h2:mem:currency-db
    user: sa
    password: password
    driverClassName: org.h2.Driver
  output:
    ansi:
      enabled: ALWAYS
  h2:
    console:
      enabled: true
clients:
  coindesk:
    type: external
    apiconfig:
      url: https://api.coindesk.com
      connectionTimeOut: 10
      readTimeOut: 60
      period: 100
      maxPeriod: 3000
      maxAttempts: 3
      retryableErrors: [ 408, 409, 429, 499, 503, 504 ]
      nonRetryableErrors: [ 400, 401, 403, 404, 500 ]
springdoc:
  swagger-ui:
    enabled: true
    path: /docs/swagger-ui
  api-docs:
    enabled: true
    path: /docs/api-docs